### ISSUE TITLE
Images not downloading due to permissions issue

### ISSUE THREAD

**Issue by evanrichards** [radekosmulski/aiquizzes-anki#2]
When importing the deck, for all images I am getting the following error:
```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

I am able to see the images by clicking the included links but it would be nice to include them in the deck.

**Comment by radekosmulski** [comment]
I think you might be on an earlier version. Could you please pull and see if the problem persists? Earlier I hosted the images on GCP but decided to host them at `aiquizzes.com` due to cost, all the links in the most recent version should point directly there.

Sorry for the trouble!

**Comment by evanrichards** [comment]
You are right, worked like a charm. Thanks for posting these online, they are super helpful.
